
server:
  port: 8080

  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never


    #servlet:
    #context-path: /api/v0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/scm_db
    username: scm_user
    password: password-sifre
    driver-class-name: org.postgresql.Driver

      #main:
      #allow-circular-references: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      '[hibernate.format_sql]': true

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

logging:
  file:
    name: logs/SupplyChainManagement.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
  level:
    '[org.springframework.web]': WARN
    '[org.hibernate]': INFO
    '[com.SupplyChainManagement]': DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'

  info:
    env:
      enabled: true

  endpoint:
    health:
      show-details: always

    shutdown:
      enabled: true

SupplyChainManagement:
  app:
    jwtSecret: SCM@!23
    jwtExpirationMs: 86400000

info:
  application:
    name: 'SupplyChainManagement Backend App'
    description: 'This is SupplyChainManagement Backend Project'
    version: '@project.version@'

